- name: stopping coda daemons
  command: /home/admin/scripts/stop-hard.sh
  register: pkill_cmd
  failed_when: pkill_cmd.rc > 1

- name: Remove Config Directory
  file:
    path: /home/admin/test-coda
    state: absent

- name: Remove Snark Output Directory
  shell: /bin/rm -rf /home/admin/test-snark-worker-*

