- name: Add apt source.list
  copy:
    dest: /etc/apt/sources.list.d/coda.list
    content: "deb [trusted=yes] http://packages.o1test.net unstable main"
  become: true

- name: install package
  become: true
  apt:
    name: coda-testnet-postake-medium-curves=0.0.1-fix-turn-on-time-offset-medium-curves-0800e98f
    state: present # present for downgrades
    force: yes
    update_cache: yes


