# FIXME: run_once doesn't work in free

- name: "get proving url from secretsmanager"
  shell: "aws secretsmanager get-secret-value --secret-id 'testnet/proving/s3_url'"
  register: proving_url
  delegate_to: 127.0.0.1
- set_fact:
    proving_url: "{{ proving_url.stdout | from_json | json_query('SecretString')  }}"

- name: "get elasticsearch endpoint from secretsmanager"
  shell: "aws secretsmanager get-secret-value --secret-id 'testnet/elasticstack'"
  register: elasticstack
  delegate_to: 127.0.0.1

- set_fact:
    elasticstack_data: " {{ elasticstack.stdout | from_json | json_query('SecretString')}} "

#- debug:
#    msg: elasticstack_data == {{ elasticstack_data }}

- set_fact:
    elastic_url: "{{ elasticstack_data | from_json | json_query('elastic') }}"
- set_fact:
    kibana_url:  "{{ elasticstack_data | from_json | json_query('kibana') }}"
