---
- hosts: "tag_testnet_{{ netname }}"
  gather_facts: no
  run_once: True
  tasks:
    - include: tasks/task-secretmanager.yaml

- hosts: "tag_testnet_{{ netname }}"
  gather_facts: no
  tasks:
    - ec2_metadata_facts:
    - name: Generating coda_start.sh
      vars:
        seed_ip: "{{ hostvars[groups['tag_role_' + netname + '_seed'][0]].ec2_ip_address }}"
        snark_leader_ip: "{{ hostvars[groups['tag_role_' + netname + '_snarker'][0]].ec2_ip_address }}"
        testnet_timestamp: "{{ start_time }}"
      template: "src=coda_start.sh.j2 dest='/home/admin/coda_start.sh' owner=admin group=admin mode=0755"
      tags: coda_start
    - pause:
        seconds: 5

- hosts: "tag_role_{{ netname }}_seed"
  gather_facts: no
  tasks:
    - name: Start Coda
      shell: /home/admin/coda_start.sh
      args:
        executable: /bin/bash
      register: seed_start
    - debug: msg="{{ seed_start.stdout }}"
    - pause:
        seconds: 30

- hosts: "tag_role_{{ netname }}_snarker"
  gather_facts: no
  tasks:
    - name: Start Coda
      shell: /home/admin/coda_start.sh
      args:
        executable: /bin/bash
      register: snarker_start
    - debug: msg="{{ snarker_start.stdout }}"
    - pause:
        seconds: 5

- hosts: "tag_role_{{ netname }}_proposer"
  gather_facts: no
  tasks:
    - name: Start Coda
      shell: /home/admin/coda_start.sh
      args:
        executable: /bin/bash
      register: proposer_start
    - debug: msg="{{ proposer_start.stdout }}"
