---
- hosts: all
  gather_facts: yes
  tasks:
    - name: Get build
      shell: dpkg -l | grep coda-testnet  | awk '{print $3}'
      register: coda_build_before

    - name: Update coda-testnet-postake package
      become: true
      apt:
        name: coda-testnet-postake
        state: latest
        update_cache: yes

    - name: Get build
      shell: dpkg -l | grep coda-testnet  | awk '{print $3}'
      register: coda_build_after
    - debug:
        msg: "Before:{{ coda_build_before.stdout }} After: {{coda_build_after.stdout }} Host:{{ansible_hostname}} "
