---
- hosts: all
  tasks:


   - name: log
     shell: journalctl -u coda* > /tmp/coda.log
     register: cmdln
     check_mode: no
     ignore_errors: yes
     changed_when: false

   - name: compress
     shell: gzip -f /tmp/coda.log
     register: cmdln
     check_mode: no
     ignore_errors: yes
     changed_when: false


   - name: fetch
     fetch:
       src: /tmp/coda.log.gz
       dest: logcapture/codalogs-{{ inventory_hostname }}.log.gz
       flat: yes
