---
- hosts: all
  tasks:
   - name: capture perf
     shell: sudo perf record -F 500  -p `pgrep -f 'coda daemon'` -g -- sleep 60
     register: cmdln
     check_mode: no
     ignore_errors: yes
     changed_when: false
   - debug: var=cmdln.stdout_lines
