---
- hosts: all
  gather_facts: yes
  tasks:
    - name: Get build
      shell: dpkg -l | grep coda-testnet  | awk '{print $3}'
      register: coda_build

    - name: Get sha
      shell: coda client status -j  | jq .commit_id
      register: coda_sha
    - debug:
        msg: "{{ansible_hostname}}\nVersion: {{ coda_build.stdout }}\nSHA: {{coda_sha.stdout }}"

    - name: Get status
      shell: /home/admin/testing/status.py
      register: result
    - pause:
        prompt: "Pausing"
    - debug:
        msg: "{{ansible_hostname}}\n {{result.stdout}}\n"
